[workspace]
members = [
    "aoc-runner",
    "aoc-runner-derive",
    "aoc-runner-internal",
    "cargo-aoc",
]
exclude = ["examples"]
resolver = "2"


[patch.crates-io]
aoc-runner-internal = { path = "aoc-runner-internal" }
